extends: 'airbnb'
plugins:
  - mozilla

rules:
  indent: [1, 2, {SwitchCase: 1}]
  mozilla/balanced-listeners: [0]
  mozilla/no-aArgs: [1]
  mozilla/this-top-level-scope: [1]
  no-console: [1]
  import/no-unresolved: [0]

globals:
  require: false
  exports: true
  uneval: false
